Update Monk to latest version
Automattic/mydb-driver pull request #3
Opened 2023-03-22 08:30 UTC by thedebian

### Summary

This PR updates Monk to the latest version, removing a lot of dependencies and vulnerabilities.

### Testing

* Spawn redis and mongo on your cloudup-vm
* `npm install`
* `make test`
* ✅ Tests should pass

Also test alongside Automattic/thumbs-up#25

2023-03-23 15:36 UTC, jgcaruso requested changes
I'm getting a test failure, I wonder if something changed in mongodb versions? I made sure that my docker container was running with redis and mongo though, so it should be the same version you were running.

<img width="694" alt="image" src="https://user-images.githubusercontent.com/4081020/227253354-7fe2cfe0-2abd-41f1-9968-54c163e46a22.png">

2023-03-24 09:07 UTC, thedebian commented
> I'm getting a test failure, I wonder if something changed in mongodb versions? I made sure that my docker container was running with redis and mongo though, so it should be the same version you were running.
> 
> <img alt="image" width="694" src="https://user-images.githubusercontent.com/4081020/227253354-7fe2cfe0-2abd-41f1-9968-54c163e46a22.png">

That's weird, according to [the documentation](https://www.mongodb.com/docs/manual/reference/operator/update/set/#behavior) "Starting in MongoDB 5.0, [mongod](https://www.mongodb.com/docs/manual/reference/program/mongod/#mongodb-binary-bin.mongod) no longer raises an error when you use an update operator like [$set](https://www.mongodb.com/docs/manual/reference/operator/update/set/#mongodb-update-up.-set) with an empty operand expression ( { } ). An empty update results in no changes and no [oplog](https://www.mongodb.com/docs/manual/reference/glossary/#std-term-oplog) entry is created (meaning that the operation is a no-op)." (and it seems I didn't change this update anyway).

I'll check, either to try the new param we're sending on connection create (the one I don't remember the name), or to update the test to set something, and check/update if there are empty $set in code using mydb-driver

2023-03-24 14:48 UTC, pgk requested changes
Test passed for me, though the process "hanged". Some feedback on eventEmitter

2023-03-24 14:48 UTC, pgk commented on index.js
> +Collection.prototype.ensureEventEmitterExists = function() {
Is this somehting we added for compatibility reasons? If not, it feels like it's use could be more of a lazyload getter. That returns the emitter.

2023-03-24 14:48 UTC, pgk commented on index.js
> +  return this._eventEmitter.on( ...arguments );
If the above comment is true and we choose to make emiter a lazy getter, this and the following can be replaced with 
```js
  this.getEventEmitter().on( ...arguments );
```

2023-03-24 14:54 UTC, pgk approved these changes
does the thing!

2023-03-27 14:21 UTC, jgcaruso approved these changes
`make test` passes after upgrading local mongodb to v6.

2023-03-27 15:00 UTC, merged